/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university_management_system;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aayush
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        back_2 = new javax.swing.JButton();
        add_employee_2 = new javax.swing.JButton();
        TITLE1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        show_table_button = new javax.swing.JButton();
        TITLE2 = new javax.swing.JLabel();
        emp_delete = new javax.swing.JTextField();
        back_3 = new javax.swing.JButton();
        update_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_2.setBackground(new java.awt.Color(152, 201, 45));
        back_2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        back_2.setForeground(new java.awt.Color(21, 25, 28));
        back_2.setText("Back");
        back_2.setBorder(null);
        back_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_2.setFocusPainted(false);
        back_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_2ActionPerformed(evt);
            }
        });
        jPanel6.add(back_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 290, 40));

        add_employee_2.setBackground(new java.awt.Color(152, 201, 45));
        add_employee_2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_employee_2.setForeground(new java.awt.Color(21, 25, 28));
        add_employee_2.setText("ADD NEW Employee");
        add_employee_2.setBorder(null);
        add_employee_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_employee_2.setFocusPainted(false);
        add_employee_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employee_2ActionPerformed(evt);
            }
        });
        jPanel6.add(add_employee_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 290, 40));

        TITLE1.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        TITLE1.setForeground(new java.awt.Color(169, 224, 49));
        TITLE1.setText("EMPLOYEE DETAILS");
        jPanel6.add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 250, 50));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(169, 224, 49));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Id", "Name", "Age", "Date Of Birth", "Address", "Phone", "E-Mail", "Aadhar", "Course", "Department", "Qualification", "Position"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 970, 240));

        show_table_button.setBackground(new java.awt.Color(152, 201, 45));
        show_table_button.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        show_table_button.setForeground(new java.awt.Color(21, 25, 28));
        show_table_button.setText("Show Data");
        show_table_button.setBorder(null);
        show_table_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_table_button.setFocusPainted(false);
        show_table_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_table_buttonActionPerformed(evt);
            }
        });
        jPanel6.add(show_table_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 150, 40));

        TITLE2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TITLE2.setForeground(new java.awt.Color(169, 224, 49));
        TITLE2.setText("Enter Employee Id which Is To Be Deleted:");
        jPanel6.add(TITLE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        emp_delete.setBackground(new java.awt.Color(31, 36, 42));
        emp_delete.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        emp_delete.setForeground(new java.awt.Color(255, 255, 255));
        emp_delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        emp_delete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                emp_deleteMouseMoved(evt);
            }
        });
        emp_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_deleteActionPerformed(evt);
            }
        });
        jPanel6.add(emp_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 170, 40));

        back_3.setBackground(new java.awt.Color(152, 201, 45));
        back_3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        back_3.setForeground(new java.awt.Color(21, 25, 28));
        back_3.setText("Delete");
        back_3.setBorder(null);
        back_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_3.setFocusPainted(false);
        back_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_3ActionPerformed(evt);
            }
        });
        jPanel6.add(back_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 150, 40));

        update_button.setBackground(new java.awt.Color(152, 201, 45));
        update_button.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        update_button.setForeground(new java.awt.Color(21, 25, 28));
        update_button.setText("UPDATE Employee");
        update_button.setBorder(null);
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.setFocusPainted(false);
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel6.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(320, 50, 1190, 631);
    }// </editor-fold>//GEN-END:initComponents

    private void back_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_2ActionPerformed
        this.setVisible(false);
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_back_2ActionPerformed

    private void add_employee_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employee_2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        new Add_Employee().setVisible(true);
    }//GEN-LAST:event_add_employee_2ActionPerformed

    private void show_table_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_table_buttonActionPerformed
        try{
            database_connection cc7= new database_connection();
            String Query="select * from employee";
            java.sql.ResultSet rs1 = cc7.stat.executeQuery(Query);
            while(rs1.next())
            {
                String rollno=rs1.getString("emp_id");
                String name=rs1.getString("name");
                String age=rs1.getString("age");
                String dob=rs1.getString("dob");
                String address=rs1.getString("address");
                String phone=rs1.getString("phone");
                String email=rs1.getString("email");
                String aadhar=rs1.getString("aadhar");
                String course=rs1.getString("course");
                String dept=rs1.getString("dept");
                String highest_qualification=rs1.getString("highest_qualification");
                String position=rs1.getString("position");
                String tbdata[]={rollno,name,age,dob,address,phone,email,aadhar,course,dept,highest_qualification,position};
                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbdata);
            }
        }catch(HeadlessException | SQLException ff){
            JOptionPane.showMessageDialog(null,"Can't Find Employee Id Please Check Again");
            System.out.println("The error is:"+ff);
        }
    }//GEN-LAST:event_show_table_buttonActionPerformed

    private void emp_deleteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_deleteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_deleteMouseMoved

    private void emp_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_deleteActionPerformed

    private void back_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_3ActionPerformed
        database_connection c1 = new database_connection();
        try{
            String roll=emp_delete.getText();
            String q = "delete from employee where emp_id = '"+roll+"'";
            c1.stat.executeUpdate(q);
            this.setVisible(false);
            new EmployeeDetails().setVisible(true);
        }catch(SQLException e){}
    }//GEN-LAST:event_back_3ActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateEmployeeDetails().setVisible(true);
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TITLE1;
    public javax.swing.JLabel TITLE2;
    private javax.swing.JButton add_employee_2;
    private javax.swing.JButton back_2;
    private javax.swing.JButton back_3;
    private javax.swing.JTextField emp_delete;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton show_table_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
