/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university_management_system;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aayush
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        TITLE1 = new javax.swing.JLabel();
        employee_att = new javax.swing.JButton();
        update_student = new javax.swing.JButton();
        delete_student = new javax.swing.JButton();
        Add_Student3 = new javax.swing.JButton();
        upd_marks = new javax.swing.JButton();
        Print_res = new javax.swing.JButton();
        atudent_att = new javax.swing.JButton();
        Add_employee = new javax.swing.JButton();
        update_employees = new javax.swing.JButton();
        delete_employee = new javax.swing.JButton();
        emp_salary = new javax.swing.JButton();
        fees_details = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_att1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setForeground(new java.awt.Color(0, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        TITLE1.setForeground(new java.awt.Color(169, 224, 49));
        TITLE1.setText("UNIVERSITY MANAGEMENT SYSTEM");
        jPanel6.add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 630, 60));

        employee_att.setBackground(new java.awt.Color(152, 201, 45));
        employee_att.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        employee_att.setForeground(new java.awt.Color(21, 25, 28));
        employee_att.setText("EMPLOYEE ATTENDANCE");
        employee_att.setBorder(null);
        employee_att.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee_att.setFocusPainted(false);
        employee_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_attActionPerformed(evt);
            }
        });
        jPanel6.add(employee_att, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 290, 70));

        update_student.setBackground(new java.awt.Color(152, 201, 45));
        update_student.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        update_student.setForeground(new java.awt.Color(21, 25, 28));
        update_student.setText("UPDATE STUDENT DETAILS");
        update_student.setBorder(null);
        update_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_student.setFocusPainted(false);
        update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_studentActionPerformed(evt);
            }
        });
        jPanel6.add(update_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 290, 70));

        delete_student.setBackground(new java.awt.Color(152, 201, 45));
        delete_student.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        delete_student.setForeground(new java.awt.Color(21, 25, 28));
        delete_student.setText("DELETE STUDENT");
        delete_student.setBorder(null);
        delete_student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_student.setFocusPainted(false);
        delete_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_studentActionPerformed(evt);
            }
        });
        jPanel6.add(delete_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 290, 70));

        Add_Student3.setBackground(new java.awt.Color(152, 201, 45));
        Add_Student3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Add_Student3.setForeground(new java.awt.Color(21, 25, 28));
        Add_Student3.setText("ADD STUDENT");
        Add_Student3.setBorder(null);
        Add_Student3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Student3.setFocusPainted(false);
        Add_Student3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Student3ActionPerformed(evt);
            }
        });
        jPanel6.add(Add_Student3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 290, 70));

        upd_marks.setBackground(new java.awt.Color(152, 201, 45));
        upd_marks.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        upd_marks.setForeground(new java.awt.Color(21, 25, 28));
        upd_marks.setText("UPDATE MARKS");
        upd_marks.setBorder(null);
        upd_marks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upd_marks.setFocusPainted(false);
        upd_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_marksActionPerformed(evt);
            }
        });
        jPanel6.add(upd_marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 290, 70));

        Print_res.setBackground(new java.awt.Color(152, 201, 45));
        Print_res.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Print_res.setForeground(new java.awt.Color(21, 25, 28));
        Print_res.setText("STUDENT RESULT");
        Print_res.setBorder(null);
        Print_res.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Print_res.setFocusPainted(false);
        Print_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_resActionPerformed(evt);
            }
        });
        jPanel6.add(Print_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 290, 70));

        atudent_att.setBackground(new java.awt.Color(152, 201, 45));
        atudent_att.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        atudent_att.setForeground(new java.awt.Color(21, 25, 28));
        atudent_att.setText("STUDENT ATTENDANCE");
        atudent_att.setBorder(null);
        atudent_att.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atudent_att.setFocusPainted(false);
        atudent_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atudent_attActionPerformed(evt);
            }
        });
        jPanel6.add(atudent_att, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 710, 290, 70));

        Add_employee.setBackground(new java.awt.Color(152, 201, 45));
        Add_employee.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Add_employee.setForeground(new java.awt.Color(21, 25, 28));
        Add_employee.setText("ADD EMPLOYEE");
        Add_employee.setBorder(null);
        Add_employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_employee.setFocusPainted(false);
        Add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_employeeActionPerformed(evt);
            }
        });
        jPanel6.add(Add_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 290, 70));

        update_employees.setBackground(new java.awt.Color(152, 201, 45));
        update_employees.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        update_employees.setForeground(new java.awt.Color(21, 25, 28));
        update_employees.setText("UPDATE EMPLOYEE DETAILS");
        update_employees.setBorder(null);
        update_employees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_employees.setFocusPainted(false);
        update_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_employeesActionPerformed(evt);
            }
        });
        jPanel6.add(update_employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 290, 70));

        delete_employee.setBackground(new java.awt.Color(152, 201, 45));
        delete_employee.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        delete_employee.setForeground(new java.awt.Color(21, 25, 28));
        delete_employee.setText("DELETE EMPLOYEE");
        delete_employee.setBorder(null);
        delete_employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_employee.setFocusPainted(false);
        delete_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_employeeActionPerformed(evt);
            }
        });
        jPanel6.add(delete_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 290, 70));

        emp_salary.setBackground(new java.awt.Color(152, 201, 45));
        emp_salary.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        emp_salary.setForeground(new java.awt.Color(21, 25, 28));
        emp_salary.setText("EMPLOYEE SALARY");
        emp_salary.setBorder(null);
        emp_salary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emp_salary.setFocusPainted(false);
        jPanel6.add(emp_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 290, 70));

        fees_details.setBackground(new java.awt.Color(152, 201, 45));
        fees_details.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fees_details.setForeground(new java.awt.Color(21, 25, 28));
        fees_details.setText("FEES DETAILS");
        fees_details.setBorder(null);
        fees_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fees_details.setFocusPainted(false);
        jPanel6.add(fees_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 290, 70));
        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 10, 1070));

        employee_att1.setBackground(new java.awt.Color(152, 201, 45));
        employee_att1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        employee_att1.setForeground(new java.awt.Color(21, 25, 28));
        employee_att1.setText("LOGOUT");
        employee_att1.setBorder(null);
        employee_att1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee_att1.setFocusPainted(false);
        employee_att1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_att1ActionPerformed(evt);
            }
        });
        jPanel6.add(employee_att1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        setBounds(150, 0, 1153, 1133);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Student3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Student3ActionPerformed
        new ad_st().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_Student3ActionPerformed

    private void Add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_employeeActionPerformed
        new Add_Employee().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_employeeActionPerformed

    private void update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_studentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentDetails().setVisible(true);
    }//GEN-LAST:event_update_studentActionPerformed

    private void update_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_employeesActionPerformed
        // TODO add your handling code here:
        new EmployeeDetails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_update_employeesActionPerformed

    private void delete_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_studentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentDetails().setVisible(true);
    }//GEN-LAST:event_delete_studentActionPerformed

    private void delete_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_employeeActionPerformed
        // TODO add your handling code here:
        new EmployeeDetails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_delete_employeeActionPerformed

    private void upd_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_marksActionPerformed
        // TODO add your handling code here:
        new Student_Marks().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_upd_marksActionPerformed

    private void Print_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_resActionPerformed
        // TODO add your handling code here:
        new Resultchk().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Print_resActionPerformed

    private void employee_att1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_att1ActionPerformed
        new AdminSignIn().setVisible(true);
        try {
            Thread.sleep(250);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_employee_att1ActionPerformed

    private void atudent_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atudent_attActionPerformed
        // TODO add your handling code here:
        new Student_Attendance().setVisible(true);
        
        try {
            Thread.sleep(250);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_atudent_attActionPerformed

    private void employee_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_attActionPerformed
        // TODO add your handling code here:
        new Student_Attendance().setVisible(true);
        
        try {
            Thread.sleep(250);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_employee_attActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Student3;
    private javax.swing.JButton Add_employee;
    private javax.swing.JButton Print_res;
    public javax.swing.JLabel TITLE1;
    private javax.swing.JButton atudent_att;
    private javax.swing.JButton delete_employee;
    private javax.swing.JButton delete_student;
    private javax.swing.JButton emp_salary;
    private javax.swing.JButton employee_att;
    private javax.swing.JButton employee_att1;
    private javax.swing.JButton fees_details;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton upd_marks;
    private javax.swing.JButton update_employees;
    private javax.swing.JButton update_student;
    // End of variables declaration//GEN-END:variables
}
