/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university_management_system;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aayush
 */
public class Resultchk extends javax.swing.JFrame {

    /**
     * Creates new form Resultchk
     */
    public Resultchk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        marks1 = new javax.swing.JTextField();
        rollno11 = new javax.swing.JLabel();
        name11 = new javax.swing.JLabel();
        back_2 = new javax.swing.JButton();
        roll = new javax.swing.JLabel();
        rollno4 = new javax.swing.JTextField();
        sub1 = new javax.swing.JTextField();
        marks2 = new javax.swing.JTextField();
        marks3 = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        rollno13 = new javax.swing.JLabel();
        rollno14 = new javax.swing.JLabel();
        rollno16 = new javax.swing.JLabel();
        rollno17 = new javax.swing.JLabel();
        rollno18 = new javax.swing.JLabel();
        rollno12 = new javax.swing.JLabel();
        add_employee_2 = new javax.swing.JButton();
        marks5 = new javax.swing.JTextField();
        marks4 = new javax.swing.JTextField();
        TITLE1 = new javax.swing.JLabel();
        rollno15 = new javax.swing.JLabel();
        sub4 = new javax.swing.JTextField();
        sub5 = new javax.swing.JTextField();
        rollno19 = new javax.swing.JLabel();
        rollno20 = new javax.swing.JLabel();
        total_marks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marks1.setBackground(new java.awt.Color(31, 36, 42));
        marks1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        marks1.setForeground(new java.awt.Color(255, 255, 255));
        marks1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(marks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 160, 40));

        rollno11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno11.setForeground(new java.awt.Color(169, 224, 49));
        rollno11.setText("Marks");
        jPanel6.add(rollno11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 90, 20));

        name11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        name11.setForeground(new java.awt.Color(169, 224, 49));
        name11.setText("Subject1");
        jPanel6.add(name11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 20));

        back_2.setBackground(new java.awt.Color(152, 201, 45));
        back_2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        back_2.setForeground(new java.awt.Color(21, 25, 28));
        back_2.setText("Show Result");
        back_2.setBorder(null);
        back_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_2.setFocusPainted(false);
        back_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_2ActionPerformed(evt);
            }
        });
        jPanel6.add(back_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 290, 40));

        roll.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        roll.setForeground(new java.awt.Color(169, 224, 49));
        roll.setText("ROLL NO.");
        jPanel6.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 100, 20));

        rollno4.setBackground(new java.awt.Color(31, 36, 42));
        rollno4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rollno4.setForeground(new java.awt.Color(255, 255, 255));
        rollno4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        rollno4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rollno4MouseMoved(evt);
            }
        });
        jPanel6.add(rollno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 160, 40));

        sub1.setBackground(new java.awt.Color(31, 36, 42));
        sub1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sub1.setForeground(new java.awt.Color(255, 255, 255));
        sub1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 40));

        marks2.setBackground(new java.awt.Color(31, 36, 42));
        marks2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        marks2.setForeground(new java.awt.Color(255, 255, 255));
        marks2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        marks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks2ActionPerformed(evt);
            }
        });
        jPanel6.add(marks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 160, 40));

        marks3.setBackground(new java.awt.Color(31, 36, 42));
        marks3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        marks3.setForeground(new java.awt.Color(255, 255, 255));
        marks3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        marks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks3ActionPerformed(evt);
            }
        });
        jPanel6.add(marks3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 160, 40));

        sub2.setBackground(new java.awt.Color(31, 36, 42));
        sub2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sub2.setForeground(new java.awt.Color(255, 255, 255));
        sub2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 40));

        sub3.setBackground(new java.awt.Color(31, 36, 42));
        sub3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sub3.setForeground(new java.awt.Color(255, 255, 255));
        sub3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 40));

        rollno13.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno13.setForeground(new java.awt.Color(169, 224, 49));
        rollno13.setText("Marks");
        jPanel6.add(rollno13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, 20));

        rollno14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno14.setForeground(new java.awt.Color(169, 224, 49));
        rollno14.setText("Marks");
        jPanel6.add(rollno14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 90, 20));

        rollno16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno16.setForeground(new java.awt.Color(169, 224, 49));
        rollno16.setText("Marks");
        jPanel6.add(rollno16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, 20));

        rollno17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno17.setForeground(new java.awt.Color(169, 224, 49));
        rollno17.setText("Subject2");
        jPanel6.add(rollno17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, 20));

        rollno18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno18.setForeground(new java.awt.Color(169, 224, 49));
        rollno18.setText("Subject3");
        jPanel6.add(rollno18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, 20));

        rollno12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno12.setForeground(new java.awt.Color(169, 224, 49));
        rollno12.setText("Total");
        jPanel6.add(rollno12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 100, 20));

        add_employee_2.setBackground(new java.awt.Color(152, 201, 45));
        add_employee_2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_employee_2.setForeground(new java.awt.Color(21, 25, 28));
        add_employee_2.setText("Check Another Result");
        add_employee_2.setBorder(null);
        add_employee_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_employee_2.setFocusPainted(false);
        add_employee_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employee_2ActionPerformed(evt);
            }
        });
        jPanel6.add(add_employee_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 290, 40));

        marks5.setBackground(new java.awt.Color(31, 36, 42));
        marks5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        marks5.setForeground(new java.awt.Color(255, 255, 255));
        marks5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        marks5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks5ActionPerformed(evt);
            }
        });
        jPanel6.add(marks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 160, 40));

        marks4.setBackground(new java.awt.Color(31, 36, 42));
        marks4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        marks4.setForeground(new java.awt.Color(255, 255, 255));
        marks4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        marks4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                marks4MouseMoved(evt);
            }
        });
        marks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks4ActionPerformed(evt);
            }
        });
        jPanel6.add(marks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 160, 40));

        TITLE1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        TITLE1.setForeground(new java.awt.Color(169, 224, 49));
        TITLE1.setText("REPORT CARD");
        jPanel6.add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 240, -1));

        rollno15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno15.setForeground(new java.awt.Color(169, 224, 49));
        rollno15.setText("Subject4");
        jPanel6.add(rollno15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 90, 20));

        sub4.setBackground(new java.awt.Color(31, 36, 42));
        sub4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sub4.setForeground(new java.awt.Color(255, 255, 255));
        sub4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 160, 40));

        sub5.setBackground(new java.awt.Color(31, 36, 42));
        sub5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sub5.setForeground(new java.awt.Color(255, 255, 255));
        sub5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        sub5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sub5MouseMoved(evt);
            }
        });
        jPanel6.add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 160, 40));

        rollno19.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno19.setForeground(new java.awt.Color(169, 224, 49));
        rollno19.setText("Marks");
        jPanel6.add(rollno19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 90, 20));

        rollno20.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno20.setForeground(new java.awt.Color(169, 224, 49));
        rollno20.setText("Subject5");
        jPanel6.add(rollno20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 100, 20));

        total_marks.setBackground(new java.awt.Color(31, 36, 42));
        total_marks.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        total_marks.setForeground(new java.awt.Color(255, 255, 255));
        total_marks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        total_marks.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                total_marksMouseMoved(evt);
            }
        });
        total_marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_marksActionPerformed(evt);
            }
        });
        jPanel6.add(total_marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(320, 50, 740, 594);
    }// </editor-fold>//GEN-END:initComponents

    private void back_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_2ActionPerformed
        try{
           database_connection cc7= new database_connection();
           String roll_no=rollno4.getText();
           
           String query1="select * from subject where rollno='"+roll_no+"'";
           System.out.println(query1);
           ResultSet rs1 = cc7.stat.executeQuery(query1);
           //String query = "insert into employee values('"+A1+"','"+A2+"','"+A3+"','"+A4+"','"+A5+"','"+A6+"','"+A7+"','"+A8+"','"+A9+"','"+A10+"','"+A11+"','"+A12+"')";
           if(rs1.next()){
               String vv1=rs1.getString("subject1");
               String vv2=rs1.getString("subject2");
               String vv3=rs1.getString("subject3");
               String vv4=rs1.getString("subject4");
               String vv5=rs1.getString("subject5");
               sub1.setText(vv1);
               sub2.setText(vv2);
               sub3.setText(vv3);
               sub4.setText(vv4);
               sub5.setText(vv5);
           }
           
           String query2="select * from marks where rollno='"+roll_no+"'";
           ResultSet rs2 = cc7.stat.executeQuery(query2);
           
           if(rs2.next()){
               String vs1=rs2.getString("marks1");
               String vs2=rs2.getString("marks2");
               String vs3=rs2.getString("marks3");
               String vs4=rs2.getString("marks4");
               String vs5=rs2.getString("marks5");
               int marks12=Integer.parseInt(vs1);
               int marks22=Integer.parseInt(vs2);
               int marks32=Integer.parseInt(vs3);
               int marks42=Integer.parseInt(vs4);
               int marks52=Integer.parseInt(vs5);
               marks1.setText(vs1);
               marks2.setText(vs2);
               marks3.setText(vs3);
               marks4.setText(vs4);
               marks5.setText(vs5);
               int total=marks12+marks22+marks32+marks42+marks52;
               total_marks.setText(total+"/500");
           }
         
       }catch(HeadlessException | SQLException ff){
            JOptionPane.showMessageDialog(null,"Can't Find Roll No Please Check Again");
            System.out.println("The error is:"+ff);
        }
    }//GEN-LAST:event_back_2ActionPerformed

    private void rollno4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rollno4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rollno4MouseMoved

    private void add_employee_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employee_2ActionPerformed

        rollno4.setText("");
        sub1.setText("");
        sub2.setText("");
        sub3.setText("");
        sub4.setText("");
        sub5.setText("");
        marks1.setText("");
        marks2.setText("");
        marks3.setText("");
        marks4.setText("");
        marks5.setText("");
        JOptionPane.showMessageDialog(null,"Please Enter Another Roll No");
    }//GEN-LAST:event_add_employee_2ActionPerformed

    private void marks5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks5ActionPerformed

    private void marks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks4ActionPerformed

    private void marks4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marks4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_marks4MouseMoved

    private void marks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks3ActionPerformed

    private void marks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks2ActionPerformed

    private void total_marksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_marksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_marksActionPerformed

    private void total_marksMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_marksMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_total_marksMouseMoved

    private void sub5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5MouseMoved

    /**
     * @param args the command line arguments
     */
    //System.out.println("I'm Loser");
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultchk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultchk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultchk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultchk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultchk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TITLE1;
    private javax.swing.JButton add_employee_2;
    private javax.swing.JButton back_2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField marks1;
    private javax.swing.JTextField marks2;
    private javax.swing.JTextField marks3;
    private javax.swing.JTextField marks4;
    private javax.swing.JTextField marks5;
    private javax.swing.JLabel name11;
    private javax.swing.JLabel roll;
    private javax.swing.JLabel rollno11;
    private javax.swing.JLabel rollno12;
    private javax.swing.JLabel rollno13;
    private javax.swing.JLabel rollno14;
    private javax.swing.JLabel rollno15;
    private javax.swing.JLabel rollno16;
    private javax.swing.JLabel rollno17;
    private javax.swing.JLabel rollno18;
    private javax.swing.JLabel rollno19;
    private javax.swing.JLabel rollno20;
    private javax.swing.JTextField rollno4;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub4;
    private javax.swing.JTextField sub5;
    private javax.swing.JTextField total_marks;
    // End of variables declaration//GEN-END:variables
}
