/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university_management_system;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Aayush
 */
public class UpdateStudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudentDetails
     */
    public UpdateStudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        father_name1 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        rollno11 = new javax.swing.JLabel();
        name11 = new javax.swing.JLabel();
        fathername11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        name12 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        roll = new javax.swing.JLabel();
        rollno1 = new javax.swing.JTextField();
        dob1 = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        class_10 = new javax.swing.JTextField();
        aadhar1 = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        rollno13 = new javax.swing.JLabel();
        rollno14 = new javax.swing.JLabel();
        rollno15 = new javax.swing.JLabel();
        rollno16 = new javax.swing.JLabel();
        rollno17 = new javax.swing.JLabel();
        rollno18 = new javax.swing.JLabel();
        rollno19 = new javax.swing.JLabel();
        rollno12 = new javax.swing.JLabel();
        class_12 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        course1 = new javax.swing.JTextField();
        branch1 = new javax.swing.JTextField();
        TITLE1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        father_name1.setBackground(new java.awt.Color(31, 36, 42));
        father_name1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        father_name1.setForeground(new java.awt.Color(255, 255, 255));
        father_name1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        father_name1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                father_name1MouseMoved(evt);
            }
        });
        father_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father_name1ActionPerformed(evt);
            }
        });
        jPanel6.add(father_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 160, 40));

        age1.setBackground(new java.awt.Color(31, 36, 42));
        age1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        age1.setForeground(new java.awt.Color(255, 255, 255));
        age1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        age1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                age1MouseMoved(evt);
            }
        });
        jPanel6.add(age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 40));

        rollno11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno11.setForeground(new java.awt.Color(169, 224, 49));
        rollno11.setText("Branch");
        jPanel6.add(rollno11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 90, 20));

        name11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        name11.setForeground(new java.awt.Color(169, 224, 49));
        name11.setText("Age");
        jPanel6.add(name11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 20));

        fathername11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        fathername11.setForeground(new java.awt.Color(169, 224, 49));
        fathername11.setText("Father's Name");
        jPanel6.add(fathername11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, -1));

        jButton8.setBackground(new java.awt.Color(152, 201, 45));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 25, 28));
        jButton8.setText("Show Details");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 110, 40));

        name12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        name12.setForeground(new java.awt.Color(169, 224, 49));
        name12.setText("Name");
        jPanel6.add(name12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 90, 20));

        name1.setBackground(new java.awt.Color(31, 36, 42));
        name1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        name1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                name1MouseMoved(evt);
            }
        });
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel6.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 40));

        roll.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        roll.setForeground(new java.awt.Color(169, 224, 49));
        roll.setText("ROLL NO");
        jPanel6.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 20));

        rollno1.setBackground(new java.awt.Color(31, 36, 42));
        rollno1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rollno1.setForeground(new java.awt.Color(255, 255, 255));
        rollno1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        rollno1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rollno1MouseMoved(evt);
            }
        });
        rollno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollno1ActionPerformed(evt);
            }
        });
        jPanel6.add(rollno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, 40));

        dob1.setBackground(new java.awt.Color(31, 36, 42));
        dob1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        dob1.setForeground(new java.awt.Color(255, 255, 255));
        dob1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        dob1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dob1MouseMoved(evt);
            }
        });
        dob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob1ActionPerformed(evt);
            }
        });
        jPanel6.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 160, 40));

        phone1.setBackground(new java.awt.Color(31, 36, 42));
        phone1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 255, 255));
        phone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        phone1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                phone1MouseMoved(evt);
            }
        });
        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });
        jPanel6.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 160, 40));

        class_10.setBackground(new java.awt.Color(31, 36, 42));
        class_10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        class_10.setForeground(new java.awt.Color(255, 255, 255));
        class_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        class_10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                class_10MouseMoved(evt);
            }
        });
        class_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_10ActionPerformed(evt);
            }
        });
        jPanel6.add(class_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 160, 40));

        aadhar1.setBackground(new java.awt.Color(31, 36, 42));
        aadhar1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        aadhar1.setForeground(new java.awt.Color(255, 255, 255));
        aadhar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        aadhar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                aadhar1MouseMoved(evt);
            }
        });
        aadhar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhar1ActionPerformed(evt);
            }
        });
        jPanel6.add(aadhar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 160, 40));

        address1.setBackground(new java.awt.Color(31, 36, 42));
        address1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        address1.setForeground(new java.awt.Color(255, 255, 255));
        address1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        address1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                address1MouseMoved(evt);
            }
        });
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        jPanel6.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 40));

        email1.setBackground(new java.awt.Color(31, 36, 42));
        email1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        email1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                email1MouseMoved(evt);
            }
        });
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel6.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 160, 40));

        rollno13.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno13.setForeground(new java.awt.Color(169, 224, 49));
        rollno13.setText("DOB");
        jPanel6.add(rollno13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 90, 20));

        rollno14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno14.setForeground(new java.awt.Color(169, 224, 49));
        rollno14.setText("Phone");
        jPanel6.add(rollno14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 90, 20));

        rollno15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno15.setForeground(new java.awt.Color(169, 224, 49));
        rollno15.setText("Class 10");
        jPanel6.add(rollno15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 90, 20));

        rollno16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno16.setForeground(new java.awt.Color(169, 224, 49));
        rollno16.setText("AADHAR");
        jPanel6.add(rollno16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 90, 20));

        rollno17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno17.setForeground(new java.awt.Color(169, 224, 49));
        rollno17.setText("Address");
        jPanel6.add(rollno17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, 20));

        rollno18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno18.setForeground(new java.awt.Color(169, 224, 49));
        rollno18.setText("E-Mail");
        jPanel6.add(rollno18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 20));

        rollno19.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno19.setForeground(new java.awt.Color(169, 224, 49));
        rollno19.setText("Class 12");
        jPanel6.add(rollno19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 90, 20));

        rollno12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        rollno12.setForeground(new java.awt.Color(169, 224, 49));
        rollno12.setText("Course");
        jPanel6.add(rollno12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 90, 20));

        class_12.setBackground(new java.awt.Color(31, 36, 42));
        class_12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        class_12.setForeground(new java.awt.Color(255, 255, 255));
        class_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        class_12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                class_12MouseMoved(evt);
            }
        });
        class_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_12ActionPerformed(evt);
            }
        });
        jPanel6.add(class_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 160, 40));

        jButton9.setBackground(new java.awt.Color(152, 201, 45));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(21, 25, 28));
        jButton9.setText("UPDATE");
        jButton9.setBorder(null);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 290, 40));

        course1.setBackground(new java.awt.Color(31, 36, 42));
        course1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        course1.setForeground(new java.awt.Color(255, 255, 255));
        course1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        course1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                course1MouseMoved(evt);
            }
        });
        course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1ActionPerformed(evt);
            }
        });
        jPanel6.add(course1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 160, 40));

        branch1.setBackground(new java.awt.Color(31, 36, 42));
        branch1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        branch1.setForeground(new java.awt.Color(255, 255, 255));
        branch1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        branch1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                branch1MouseMoved(evt);
            }
        });
        branch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch1ActionPerformed(evt);
            }
        });
        jPanel6.add(branch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 160, 40));

        TITLE1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        TITLE1.setForeground(new java.awt.Color(169, 224, 49));
        TITLE1.setText("UPDATE STUDENT");
        jPanel6.add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, -1));

        jButton10.setBackground(new java.awt.Color(152, 201, 45));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(21, 25, 28));
        jButton10.setText("Back");
        jButton10.setBorder(null);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void father_name1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_father_name1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_father_name1MouseMoved

    private void father_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_father_name1ActionPerformed

    private void age1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_age1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_age1MouseMoved

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        try{
                String roll_upd=rollno1.getText();
                database_connection cc= new database_connection();
                String str = "select * from student where rollno = '"+roll_upd+"'";
                java.sql.ResultSet rs = cc.stat.executeQuery(str);

                if(rs.next()){
                    rollno1.setText(rs.getString(1));
                    name1.setText(rs.getString(2));
                    father_name1.setText(rs.getString(3));
                    age1.setText(rs.getString(4));
                    dob1.setText(rs.getString(5));
                   address1.setText(rs.getString(6));
                    phone1.setText(rs.getString(7));
                    email1.setText(rs.getString(8));
                    class_10.setText(rs.getString(9));
                    class_12.setText(rs.getString(10));
                    aadhar1.setText(rs.getString(11));
                    course1.setText(rs.getString(12));
                    branch1.setText(rs.getString(13));
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Student Details Does Not Exist please try again");
                }

                
            }catch(SQLException ex){}
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void name1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_name1MouseMoved

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void rollno1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rollno1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rollno1MouseMoved

    private void rollno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollno1ActionPerformed

    private void dob1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1MouseMoved

    private void dob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob1ActionPerformed

    private void phone1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1MouseMoved

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private void class_10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_class_10MouseMoved

    private void class_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_10ActionPerformed

    private void aadhar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aadhar1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhar1MouseMoved

    private void aadhar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhar1ActionPerformed

    private void address1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_address1MouseMoved

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void email1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_email1MouseMoved

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void class_12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_12MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_class_12MouseMoved

    private void class_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String A1=rollno1.getText();
        String A2=name1.getText();
        String A3=father_name1.getText();
        String A4=age1.getText();
        String A5=dob1.getText();
        String A6=address1.getText();
        String A7=phone1.getText();
        String A8=email1.getText();
        String A9=class_10.getText();
        String A10=class_12.getText();
        String A11=aadhar1.getText();
        String A12=course1.getText();
        String A13=branch1.getText();
        try{
            database_connection cc = new database_connection();
            String q = "update student set name='"+A2+"',fathers_name='"+A3+"',age='"+A4+"', dob='"+A5+"',address='"+A6+"',phone='"+A7+"',email='"+A8+"',class_x='"+A9+"',class_xii='"+A10+"',aadhar='"+A11+"',course='"+A12+"',branch='"+A13+"' where rollno='"+A1+"'";
            cc.stat.executeUpdate(q);
            JOptionPane.showMessageDialog(null,"Student Details Updated Successfully");
        }catch(HeadlessException | SQLException ff){
            System.out.println("The error is:"+ff);
    }//GEN-LAST:event_jButton9ActionPerformed
        this.setVisible(false);
        new UpdateStudentDetails().setVisible(true);
    }
    private void course1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_course1MouseMoved

    private void course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course1ActionPerformed

    private void branch1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branch1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_branch1MouseMoved

    private void branch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branch1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new EmployeeDetails().setVisible(true);
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(UpdateStudentDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TITLE1;
    private javax.swing.JTextField aadhar1;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField age1;
    private javax.swing.JTextField branch1;
    private javax.swing.JTextField class_10;
    private javax.swing.JTextField class_12;
    private javax.swing.JTextField course1;
    private javax.swing.JTextField dob1;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField father_name1;
    private javax.swing.JLabel fathername11;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel name11;
    private javax.swing.JLabel name12;
    private javax.swing.JTextField phone1;
    private javax.swing.JLabel roll;
    private javax.swing.JTextField rollno1;
    private javax.swing.JLabel rollno11;
    private javax.swing.JLabel rollno12;
    private javax.swing.JLabel rollno13;
    private javax.swing.JLabel rollno14;
    private javax.swing.JLabel rollno15;
    private javax.swing.JLabel rollno16;
    private javax.swing.JLabel rollno17;
    private javax.swing.JLabel rollno18;
    private javax.swing.JLabel rollno19;
    // End of variables declaration//GEN-END:variables
}
